apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kafka-strimzi-schedule
  namespace: velero
spec:
  schedule: "*/15 * * * *"
  template:
    includedNamespaces:
      - kafka
    snapshotMoveData: true
    storageLocation: default
    ttl: 720h0m0s
