apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: redis-partial-schedule
  namespace: velero
spec:
  schedule: "*/15 * * * *"
  template:
    includedNamespaces:
      - redis-test
    snapshotMoveData: true
    storageLocation: default
    ttl: 720h0m0s
